### ISSUE TITLE
0.52开始支持其他类型的配置并且新功能仅在新配置格式上生效

### ISSUE THREAD

**Issue by Whuihuan** [stilleshan/frps#4]
INI配置已弃用，希望下一次更新docker的时候可以环境配置配置格式，以便过渡

**Comment by YangOu3500** [comment]
同求，期待最新的toml配置的加入！

**Comment by tcpqueue** [comment]
同求，期待最新的toml配置的加入！

**Comment by tcpqueue** [comment]
已经提交更新，https://github.com/stilleshan/frps/pull/5

**Comment by stilleshan** [comment]
> 已经提交更新，#5

https://github.com/stilleshan/frps/commit/ab182ac07bd97b1d189ecce96b02e15c734402da
thanks for your PR
